# Config overrides for production.

# Production Site URL
url: https://blog.spaceduck.io

# Set your Google Analytics id to receive `pageview` events.
# To remove Google Anaylics from your page, remove the line below.
google_analytics:      UA-113710339-1

# Setting a disqus shortname will enable the comment section on
# pages with `comments: true` in the front matter.
disqus:                spaceduck


